# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwaWeather < Formula
  desc "CWA Open Data API CLI for Taiwan weather data"
  homepage "https://github.com/kerkerj/cwa-weather"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.2.2/cwa-weather_darwin_amd64.tar.gz"
      sha256 "bfdf624af0d9370def2d8f74aa9c8eab978e221a90be2f57da1f2f2780b1009f"

      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.2.2/cwa-weather_darwin_arm64.tar.gz"
      sha256 "8cbe445b6e00db5ef146f11056fdf07817b1638e7453116eeace475d9acf516a"

      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.2.2/cwa-weather_linux_amd64.tar.gz"
      sha256 "6312eb6c20c1470ffb13121505a743e0fb3f223a774a4c81df76e007c4bea40a"
      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.2.2/cwa-weather_linux_arm64.tar.gz"
      sha256 "f73fb6cdbcc211973dd2234e4764bcad8e33ef2acf2febb45df86b0645be8f9a"
      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
  end

  test do
    system "#{bin}/cwa-weather", "--version"
  end
end
