# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwaWeather < Formula
  desc "CWA Open Data API CLI for Taiwan weather data"
  homepage "https://github.com/kerkerj/cwa-weather"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.3.1/cwa-weather_darwin_amd64.tar.gz"
      sha256 "afa2725c936070f4c3ca16c5c36b4eb8f0d6fe4eb8b7065121dc95533190b82f"

      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.3.1/cwa-weather_darwin_arm64.tar.gz"
      sha256 "37dd9ab8b5d7b3f43477697d108014ee1b0bb2b2f1d9c36260bbc3d137d69a45"

      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.3.1/cwa-weather_linux_amd64.tar.gz"
      sha256 "6898fcdbd3eec6274969511ed180ce602271013da17e3bb39f9577355db28cee"
      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.3.1/cwa-weather_linux_arm64.tar.gz"
      sha256 "04e5d29bd916405fcfb9442d5fa58d2e74b8663b4d15a4ca1884420baa894a6f"
      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
  end

  test do
    system "#{bin}/cwa-weather", "--version"
  end
end
