# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwaWeather < Formula
  desc "CWA Open Data API CLI for Taiwan weather data"
  homepage "https://github.com/kerkerj/cwa-weather"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.3.0/cwa-weather_darwin_amd64.tar.gz"
      sha256 "1a28a152139b725b8726a21ff5c7dc56bd583cfbdf685536386e44beaf24328a"

      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.3.0/cwa-weather_darwin_arm64.tar.gz"
      sha256 "7a4aff0d845afc89a841be58104b4f2cc5e131ca9d15fdd7aac3b3c0e20fc8d7"

      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.3.0/cwa-weather_linux_amd64.tar.gz"
      sha256 "7a37844104b7234a71d49400f8d47404e5ba90809683067b978cbb36ae1ad142"
      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kerkerj/cwa-weather/releases/download/v0.3.0/cwa-weather_linux_arm64.tar.gz"
      sha256 "f7284815281f4808c3e17a3e9814492f8726c0604a490fbbc7e61bc006e2da39"
      define_method(:install) do
        bin.install "cwa-weather"
      end
    end
  end

  test do
    system "#{bin}/cwa-weather", "--version"
  end
end
